### ISSUE TITLE
Follow the final version of FAPI 1.0

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#144]
[Motivation]
The current keycloak (12.0.1) has supported FAPI-RW security profile which version is Implementer’s Draft ver 2(ID2). It also has passed all corresponding conformance tests on local environment.
On Jan, OID-F will fix the final version of FAPI 1.0 which have some changes compared with ID2.
IMO, we must support the final version of FAPI 1.0. 

[Additional works needed]
We need to do the following works :
- Clarify the difference between the final version and ID2
- Clarify whether additional implementation is needed
- If needed, implement features needed to support the final version of FAPI 1.0
- Confirm whether the keycloak incorporating these features can pass all conformance tests for the final version of FAPI 1.0.
- After PRs for such the implementation are merged and the new version of keycloak is released, confirm whether this version of keycloak  can pass all conformance tests for the final version of FAPI 1.0.

**Comment by jlosantana** [comment]
great news!

**Comment by rmarins** [comment]
Check out the difference between ID2 and 1.0 Final versions of the FAPI Part 2 spec:
https://github.com/rmarins/kc-sig-fapi/commit/b5a8cba4b0580aa8f1c7903dcc39d93e30e320ec?branch=b5a8cba4b0580aa8f1c7903dcc39d93e30e320ec&diff=split

**Comment by tnorimat** [comment]
@rmarins Thank you for your analysis. I've updated the working items for following the final version FAPI.
I've described it in FAPI-SIG 15th meeting. You can see its document on the following link.
https://github.com/keycloak/kc-sig-fapi/blob/master/FAPI-SIG/meetings/15th/presentations/FAPI-SIG_15th_MTG_agenda.pdf
page 6 to 9.

**Comment by tnorimat** [comment]
Theoretically, the latest keycloak can support the final version of FAPI 1.0 by https://github.com/keycloak/keycloak/pull/7910 and https://github.com/keycloak/keycloak/pull/7907 .

However, we cannot run the conformance tests supporting the final version of FAPI 1.0 conformance because the current conformance test have not yet supported this final version as mentioned in the page 7 of [FAPI-SIG 15th meeting's agenda](https://github.com/keycloak/kc-sig-fapi/blob/master/FAPI-SIG/meetings/15th/presentations/FAPI-SIG_15th_MTG_agenda.pdf).

**Comment by tnorimat** [comment]
The final objective is to run FAPI conformance suite (test plan = MTLS, Private Key / signature algorithm = PS256, ES256) for FAPI 1.0 final version against the released keycloak  and pass all tests.

To do so,  the following conditions need to be satisfied.

1. REST API specification for Client Policies is fixed.
1. Preset Client Policies for FAPI 1.0 final are determined and implemented.
1. The new version of keycloak incorporating this fixed REST API is released.
1. The new version of conformance suite for FAPI 1.0 final is released.

The current situation is as follows.

#### 1.  REST API specification for Client Policies is fixed.

Finalizing the specification is in progress.
It will be supported by keycloak 14.

- Ticket : [KEYCLOAK-14209 Client Policy : UI on old Admin Console](https://issues.redhat.com/browse/KEYCLOAK-14209)
- ML : [JSON configuration format for client policies](https://groups.google.com/g/keycloak-dev/c/MfoTQbNPljE)
- PR : [KEYCLOAK-14209 Client policies admin console support. Small changing of format of JSON for client policies and profiles. #7969](https://github.com/keycloak/keycloak/pull/7969)

#### 2. Preset Client Policies for FAPI 1.0 final are determined and implemented.

Finalizing the profiles is in progress.
It will be supported by keycloak 14.

- Ticket : [KEYCLOAK-14208 Client Policy : Pre-set Policies (including FAPI preset policies)](https://issues.redhat.com/browse/KEYCLOAK-14208)
- ML : [Default client profiles for FAPI](https://groups.google.com/g/keycloak-dev/c/Hyzib1Tm3zY)
- PR : not yet

#### 3. The new version of keycloak incorporating this fixed REST API is released.

Waiting for keycloak 14.

#### 4. The new version of conformance suite for FAPI 1.0 final is released.

Its latest tag version is 4.1.10 and it seems that it has not yet supported FAPI 1.0 final (only supported ID2).

**Comment by tnorimat** [comment]
I've tentatively push FAPI 1.0 Final supported environment onto https://github.com/keycloak/kc-sig-fapi/tree/for-fapi-1-0-final .
