### ISSUE TITLE
Wrong authentication delegation response status

### ISSUE THREAD

**Issue by elnanou** [keycloak/kc-sig-fapi#167]
I noticed that the Authentication Delegation Response status is 201 and not 204 as mentioned in the documentation.
If 204 is returned we get this error :
`OIDCException(httpStatus=503 SERVICE_UNAVAILABLE, clientExceptionContent=ClientExceptionContent(error=server_error, errorDescription=Unexpected response from authentication device))`

HttpAuthenticationChannelProvider source code :

    @Override
    public boolean requestAuthentication(CIBAAuthenticationRequest request, String infoUsedByAuthenticator) {
        // Creates JWT formatted/JWS signed/JWE encrypted Authentication Channel ID by the same manner in creating auth_req_id.
        // Authentication Channel ID binds Backchannel Authentication Request with Authentication by Authentication Device (AD).
        // JWE serialized Authentication Channel ID works as a bearer token. It includes client_id 
        // that can be used on Authentication Channel Callback Endpoint to recognize the Consumption Device (CD)
        // that sent Backchannel Authentication Request.

        // The following scopes should be displayed on AD:
        // 1. scopes specified explicitly as query parameter in the authorization request
        // 2. scopes specified implicitly as default client scope in keycloak

        checkAuthenticationChannel();

        ClientModel client = request.getClient();

        try {
            AuthenticationChannelRequest channelRequest = new AuthenticationChannelRequest();

            channelRequest.setScope(request.getScope());
            channelRequest.setBindingMessage(request.getBindingMessage());
            channelRequest.setLoginHint(infoUsedByAuthenticator);
            channelRequest.setConsentRequired(client.isConsentRequired());
            channelRequest.setAcrValues(request.getAcrValues());

            SimpleHttp simpleHttp = SimpleHttp.doPost(httpAuthenticationChannelUri, session)
                    .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON)
                    .json(channelRequest)
                    .auth(createBearerToken(request, client));
 
            int status = completeDecoupledAuthnRequest(simpleHttp, channelRequest).asStatus();

            if (status == Status.CREATED.getStatusCode()) {
                return true;
            }
        } catch (IOException ioe) {
            throw new RuntimeException("Authentication Channel Access failed.", ioe);
        }

        return false;
    }

(version : Keycloak 13.0.0)

**Comment by tnorimat** [comment]
Hello @elnanou ,
Thank you for your notification. I will fix [keycloak's documentation](https://www.keycloak.org/docs/latest/server_admin/index.html#_client_initiated_backchannel_authentication_grant) as you pointed out (not 204. 201 returned).
