### ISSUE TITLE
List of concerns keycloak

### ISSUE THREAD

**Issue by evertongodoi** [keycloak/kc-sig-fapi#208]
Hi all, I've a question about openid/concerns on keycloak, how it's possible to create a list of concerns on keycloak, with options required and no required, to select options in a list. I looked for documentation, and I created test but I can't to do this, I only got it to created a test with one option concern in a button, but I need a list. I don't know if this option with list, is necessary to create on application. If someone may be help me, I appreciate it. Thank you. (This question is about Open Banking Brazil implementation)

**Comment by tnorimat** [comment]
Hello @evertongodoi . Unfortunately, I could not clarify what a list of concerns on keycloak is. Could you elaborate it?

**Comment by evertongodoi** [comment]
@tnorimat , I found what I needed, in a client scope! tks
