### ISSUE TITLE
Dynamic or Parameter scope

### ISSUE THREAD

**Issue by evertongodoi** [keycloak/kc-sig-fapi#219]
How it's possible to enable Dynamic or Parameter scope in Keycloak ? This is necessary on the Open Banking Brazil Project, and I foundn't in the Keycloak configuration, if someone may help me I would appreciate.

**Comment by tnorimat** [comment]
Hello @evertongodoi ,

AFAIK, the current keycloak does not support dynamic or parameter scope.

Some contributor has tried to support the dynamic scope. But I'm not sure whether this dynamic scope is what you want.
You can found its discussion in https://groups.google.com/g/keycloak-dev/c/yGCWth8reNw/m/TEDYZS8hAwAJ .
Also its corresponding PR is https://github.com/keycloak/keycloak/pull/7721 .

**Comment by evertongodoi** [comment]
@tnorimat  thanks for the response, I sent a message in the Google Group discussion, and Daniel Software Engineer at RedHat, responded he that working right now in the implementation.

**Comment by thomasdarimont** [comment]
Update in this: The discussion around dynamic scope support and it's effect on RAR has resulted in a new (merged) discussion: https://github.com/keycloak/keycloak-community/pull/325

**Comment by tnorimat** [comment]
@evertongodoi The discussion continues in keycloak's repository. Therefore, I close this issue here. Thank you.
