### ISSUE TITLE
Australian CDR: fapi1-advanced-final-ensure-request-object-with-multiple-aud-succeeds fails

### ISSUE THREAD

**Issue by shaneboulden** [keycloak/kc-sig-fapi#247]
### Describe the bug

Test Name:fapi1-advanced-final-user-rejects-authentication
Variant:client_auth_type=private_key_jwt, fapi_auth_request_method=by_value, fapi_profile=consumerdataright_au, fapi_response_mode=plain_response
Description:[Manual]FAPI1-Advanced-Final: Keycloak test with private_key_jwt client authentication (RequestObject:PS256/IDToken:PS256)
Test Version:4.1.38

### Version

15.0.2

### Expected behavior

Keycloak passes the fapi1-advanced-final-ensure-request-object-with-multiple-aud-succeeds test.

### Actual behavior

Keycloak fails the test with the following errors:

ValidateIdTokenACRClaimAgainstRequest
acr value in id_token is not (one of the) requested values

actual:
```
urn:mace:incommon:iap:silver
```
expected:
```
"urn:cds.au:cdr:2"
```

### How to Reproduce?

Create a manual test plan per https://github.com/keycloak/kc-sig-fapi#run-fapi-conformance-test-plan-manually, specifying `consumerdatarights_au` for the FAPI profile. 

Run the `fapi1-advanced-final-ensure-request-object-with-multiple-aud-succeeds` test.

**Comment by tnorimat** [comment]
Hello @shaneboulden ,

Unfortunately, the current keycloak does not support Australia Consumer Data Right security profile.

However, we might resolve only the issue by modifying kc-sig-fapi/keycloak/oidf.json:
```
{
    "acr_values_supported": [ "urn:brasil:openbanking:loa2", "urn:brasil:openbanking:loa3", "urn:mace:incommon:iap:silver" ],
    "claims_supported":[ "aud", "sub", "iss", "auth_time", "name", "given_name", "family_name", "preferred_username", "email", "acr", "cpf", "cnpj" ]
}
```
to
```
{
    "acr_values_supported": [ "urn:brasil:openbanking:loa2", "urn:brasil:openbanking:loa3", "urn:mace:incommon:iap:silver", "urn:cds.au:cdr:2" ],
    "claims_supported":[ "aud", "sub", "iss", "auth_time", "name", "given_name", "family_name", "preferred_username", "email", "acr", "cpf", "cnpj" ]
}
```
and modifying kc-sig-fapi/keycloak/realm.json:
```
"claim.value": "urn:mace:incommon:iap:silver"
```
to
```
"claim.value": "urn:cds.au:cdr:2"
```

**Comment by shaneboulden** [comment]
Thanks @tnorimat! 

I've now passed this section of the test, and only have three failures now being reported: 

```
Verify authorization endpoint response: the id_token was not encrypted
Verify token endpoint response: the id_token was not encrypted
Resource server endpoint tests: AddCdrXvToResourceEndpointRequest: cdrVersion empty/missing from resource section of configuration
```
Do you know how I can configure token encryption using the FAPI test harness, and inject the cdrVersion into resource endpoint requests? Let me know if you'd like me to break these out into separate issues to track.

**Comment by tnorimat** [comment]
@shaneboulden I will check your question afterwards. As for ID token encryption, the following keycloak discussion might be helpful.
- [How to get the CEK to decrypt the ID Token?](https://github.com/keycloak/keycloak/discussions/9990)
- [How the ID Token Encryption Content Encryption Algorithm works?](https://github.com/keycloak/keycloak/discussions/9876)

The current keycloak cannot support access and refresh token encryption. It only supports ID token encryption.

**Comment by tnorimat** [comment]
@shaneboulden As for the last Resource server endpoint tests, it may not relate to an authorization server (keycloak). It may relate to a resource server (kc-fapi-sig environment sets up an API gateway powered by nginx server for a resource server).
It may be similar to [the `x-fapi-interaction-id` requirement of FAPI 1.0 baseline security profile for a resource server](https://openid.net/specs/openid-financial-api-part-1-1_0-final.html#protected-resources-provisions).

If you modify a resource server of this kc-fapi-sig environment, please refer to https://github.com/keycloak/kc-sig-fapi/blob/03467c97605f4d00c5af501bfd2bb762660e2fd9/api-gateway-nginx/fapi-verify.lua#L72-L78.

**Comment by tnorimat** [comment]
@shaneboulden If you can pass the conformance test of Australia CDR, could you feedback it to keycloak project?
It might be preferable to this feedback via our FAPI-SIG activities.

**Comment by shaneboulden** [comment]
Hi @tnorimat, thanks for your assistance with this. 

I'm now only failing two tests for the Australian CDR, though this is likely just my inexperience with the certification framework

- fapi1-advanced-final-user-rejects-authentication
- fapi1-advanced-final-ensure-request-object-signature-algorithm-is-not-none

I'll create a PR this week with an automated confformance suite config.

**Comment by shaneboulden** [comment]
Test is now passing, closing this issue
