### ISSUE TITLE
Confirm all FAPI R/W OP w/ Private key conformance tests are passed by the released keycloak

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#40]
Confirm all FAPI R/W OP w/ Private Key conformance tests are passed by the released keycloak to which all PRs for FAPI-RW are merged.

We can work with this issue after the following events :

- All PRs for FAPI-RW are merged.
- keycloak is released to which all PRs for FAPI-RW are merged.
- Container image for this version of keycloak is released.

Please note that the test environment is clarified and recorded (e.g. conformance test ver, keycloak ver, etc..).

**Comment by tnorimat** [comment]
The corresponding jira ticket is https://issues.redhat.com/browse/KEYCLOAK-10333

**Comment by arunganesh-a** [comment]
@VinodAnandan  you can assign it to me

**Comment by VinodAnandan** [comment]
Thank you @arunganesh-a

**Comment by tnorimat** [comment]
@arunganesh-a Hello. Thank you for your contribution on this issue.

On releasing the new version of keycloak (12.0.1), I've upgraded the keycloak used on this FAPI-SIG's FAPI-RW conformance test environment from 11.0.1 to 12.0.1. After that, I've run the automated conformance test by docker-compose up --build and confirmed that all FAPI-RW conformance tests have been passed against this keycloak version.

Therefore, would you mind if I could close this issue?
