### ISSUE TITLE
Integrating FAPI-RW conformance tests run into keycloak’s CI/CD pipeline

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#45]
It is helpful to run FAPI-RW conformance tests automatically on keycloak’s CI/CD pipeline like the existing arquillian integration tests.

It can keep keycloak to comply with FAPI-RW whenever any PR is merged.

It seems too much complicated to treat this task by one issue so that decomposing it into several sub tasks might be preferable.

**Comment by kannan-ra** [comment]
@pritish-nitb & @arunganesh-a can help here ... but would be nice if someone can own the task.

**Comment by tnorimat** [comment]
@kannan-ra I think it might be sufficient to use FAPI-SIG's repository to conformance tests automatically and follow new version of keycloak and conformance suite. Therefore, I close this issue. Thank you.
