### ISSUE TITLE
 FAPI-CIBA Backchannel Authentication Request : encrypt/decrypt login_hint

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#53]
[The design document for FAPI-CIBA](https://github.com/keycloak/keycloak-community/blob/master/design/client-initiated-backchannel-authentication-flow.md#request-parameters-for-user-info-conveyance) states that it requires login_hint encryption and decryption.
 However, [the current CIBA prototype implementation](https://github.com/tnorimat/keycloak/tree/ciba-prototype) does not support it.
 
 The goal of this issue is to implement on the CIBA prototype implementation login_hint encryption and decryption by following the design document for FAPI-CIBA.

**Comment by DmitryMishchuk** [comment]
Could take over this one from our team side.

**Comment by VinodAnandan** [comment]
Thank you @DmitryMishchuk

**Comment by tnorimat** [comment]
Hello @DmitryMishchuk ,

FYI, the User Resolver described in page 50 of the [CIBA Prototype Implementation Practical Guide](https://github.com/keycloak/kc-sig-fapi/blob/master/FAPI-SIG/documents/FAPI-CIBA/CIBA_PrototypeImplPracticalGuide.pdf) might be helpful.

**Comment by DmitryMishchuk** [comment]
@tnorimat It states that login_hint should be encrypted/decrypted  using client secret with AES128/192/256bit

But client_secret is an UUID it is 36 bytes long, so it is not good as a key for encryption/decryption.

**Comment by tnorimat** [comment]
Hello @DmitryMishchuk ,
IMO, `client_secret` is generated by `UUID.randomUUID().toString()` in keycloak when creating a client and according to [oracle's javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/UUID.html#randomUUID--), UUIDv4 is generated by `UUID.randomUUID().toString()` using a cryptographically strong pseudo random number generator. According to [RFC 4122](https://tools.ietf.org/html/rfc4122), UUID is 128 bits long.
Considering these points, binary representation of `client_secret` might be 128bit. It might be OK to use it for AES 128bit key.
I'm not sure what I've mentioned just above is right or not. Could you review it?

**Comment by DmitryMishchuk** [comment]
Yes you're absolutely right. Thank you.

**Comment by tnorimat** [comment]
merged. https://github.com/tnorimat/keycloak/pull/5
