### ISSUE TITLE
FAPI-CIBA Backchannel Authentication Request : support login_hint_token

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#54]
[The design document for FAPI-CIBA](https://github.com/keycloak/keycloak-community/blob/master/design/client-initiated-backchannel-authentication-flow.md) states that it requires to support login_hint_token.
 However, [the current CIBA prototype implementation](https://github.com/tnorimat/keycloak/tree/ciba-prototype) does not support it.
 
 The goal of this issue is to implement on the CIBA prototype implementation login_hint_token by following the design document for FAPI-CIBA.

**Comment by andriimurashkin** [comment]
Please assign me this ticket.

**Comment by VinodAnandan** [comment]
Thank you @andriimurashkin

**Comment by andriimurashkin** [comment]
hi @tnorima
Am I right that `login_hint_token` is a regular `access_token`?

**Comment by tnorimat** [comment]
Hello @andriimurashkin ,
Yes, keycloak's access token can satisfy the requirement specified by [the design document](https://github.com/keycloak/keycloak-community/blob/master/design/client-initiated-backchannel-authentication-flow.md#request-parameters-for-user-info-conveyance).

The CIBA standard document does not mention the details and implementation of `login_hint_token`.  Therefore I've specified on the design document the JWT base token for `login_hint_token`,

Hopefully, to make it easy to support other JWT based token as `login_hint_token` in the future, could you implement `login_hint_token` as the following multilayer style ? 
- JWT layer which is an abstract class for treating any kind of JWT style token
- Access Token  layer which is a concrete class on the JWT layer

**Comment by tnorimat** [comment]
merged. https://github.com/tnorimat/keycloak/pull/1
