### ISSUE TITLE
 FAPI-CIBA Backchannel Authentication Request : support id_token_hint

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#55]
[The design document for FAPI-CIBA](https://github.com/keycloak/keycloak-community/blob/master/design/client-initiated-backchannel-authentication-flow.md) states that it requires to support id_token_hint.
 However, [the current CIBA prototype implementation](https://github.com/tnorimat/keycloak/tree/ciba-prototype) does not support it.
 
The goal of this issue is to implement on the CIBA prototype implementation id_token_hint by following the design document for FAPI-CIBA.

**Comment by HryhoriiHevorkian** [comment]
Please assign this to me also.

**Comment by VinodAnandan** [comment]
Thank you @HryhoriiHevorkian

**Comment by tnorimat** [comment]
Hello @HryhoriiHevorkian ,

FYI, the User Resolver described in page 50 of the [CIBA Prototype Implementation Practical Guide](https://github.com/keycloak/kc-sig-fapi/blob/master/FAPI-SIG/documents/FAPI-CIBA/CIBA_PrototypeImplPracticalGuide.pdf) might be helpful.

**Comment by tnorimat** [comment]
merged. https://github.com/tnorimat/keycloak/pull/1
