### ISSUE TITLE
 FAPI-CIBA Backchannel Authentication Request : support Signed Authentication Request

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#56]
[The design document for FAPI-CIBA](https://github.com/keycloak/keycloak-community/blob/master/design/client-initiated-backchannel-authentication-flow.md#signed-authentication-request) states that it requires to support request (Signed Authentication Request).
 However, [the current CIBA prototype implementation](https://github.com/tnorimat/keycloak/tree/ciba-prototype) does not support it.
 
The goal of this issue is to implement on the CIBA prototype implementation request (Signed Authentication Request) by following the design document for FAPI-CIBA.

**Comment by kannan-ra** [comment]
@tnorimat you can assign this to @pritish-nitb (banfico)

**Comment by tnorimat** [comment]
@kannan-ra Thank you very much.
@VinodAnandan We would like to assign @pritish-nitb this issue. WDYT?

**Comment by pritish-nitb** [comment]
@tnorimat @VinodAnandan Please assign the issue to me.

**Comment by VinodAnandan** [comment]
Thank you @pritish-nitb

**Comment by tnorimat** [comment]
Hello @pritish-nitb ,

FYI, the keycloak has already supported the request object defined by OIDC. The signed authentication request seems to be the CIBA version of this request object. Therefore the existing codes for the request object might be helpful for you.

**Comment by pritish-nitb** [comment]
@tnorimat I am making changes for this issue and have following queries:
1. Do we need support for both request object and request_uri, like we have it in case of the OIDC authorization endpoint ?

2. Also, I am going by same logic for parsing the request like it has been done for OIDC authorization endpoint for parsing of query params and request object.

Also I am going to need a branch in which I can commit my changes and submit a pull request in following repo: https://github.com/tnorimat/keycloak

**Comment by tnorimat** [comment]
@pritish-nitb Hello.

> 1. Do we need support for both request object and request_uri, like we have it in case of the OIDC authorization endpoint ?

Yes, it might be preferable for us to support both request object by `request` and `request_uri`.

> 2. Also, I am going by same logic for parsing the request like it has been done for OIDC authorization endpoint for parsing of query params and request object.

Yes, we can use the same logic for handling the request object which has been already implemented at the authorization endpoint.

> Also I am going to need a branch in which I can commit my changes and submit a pull request in following repo: https://github.com/tnorimat/keycloak

Could you please use [ciba-prototype](https://github.com/tnorimat/keycloak/tree/ciba-prototype) branch?

**Comment by pritish-nitb** [comment]
@tnorimat Thanks for replying. 
Sure, I will use ciba-prototype branch.

**Comment by tnorimat** [comment]
PR sent. https://github.com/keycloak/keycloak/pull/8006
