### ISSUE TITLE
 FAPI-CIBA Backchannel Authentication Request : support User Code

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#57]
[The design document for FAPI-CIBA](https://github.com/keycloak/keycloak-community/blob/master/design/client-initiated-backchannel-authentication-flow.md#user-code) states that it requires to support user_code (User Code).
 However, [the current CIBA prototype implementation](https://github.com/tnorimat/keycloak/tree/ciba-prototype) does not support it.
 
 The goal of this issue is to implement on the CIBA prototype implementation user_code (User Code) by following the design document for FAPI-CIBA.

**Comment by HryhoriiHevorkian** [comment]
Please assign this ticket for me.

**Comment by VinodAnandan** [comment]
Thank you @HryhoriiHevorkian

**Comment by HryhoriiHevorkian** [comment]
@tnorimat could you please clarify where to store the userCode parameter? I see that UserModel does not have this field inside.

**Comment by tnorimat** [comment]
Hello, @HryhoriiHevorkian ,

User Code is used for preventing any malicious entity from sending unsolicited AuthN & AuthZ request to AD.
The end user only knows their user code (like password).
Only the entity holding this user code is a legitimate entity who receives the request from CD with the end user's permission (eg. the end user input their user code onto CD explicitly).

Considering this nature of the user code, IMO it might be better to do the following :
- keycloak does not hold and persist the user code anywhere because the user code is sensitive data.
- On receiving the user code, keycloak sends it to the Decoupled Auth Server because the Decoupled Auth Server needs to send this user code to the end user's AD. To do so, you need to add this user code to REQ-2 : AuthN & AuthZ Delegation Request defined in the page 28 of [CIBA Prototype Implementation Practical Guide](https://github.com/keycloak/kc-sig-fapi/blob/master/FAPI-SIG/documents/FAPI-CIBA/CIBA_PrototypeImplPracticalGuide.pdf).

**Comment by tnorimat** [comment]
merged. https://github.com/tnorimat/keycloak/pull/2
