### ISSUE TITLE
 FAPI-CIBA Realm Settings (CIBA Policy) overriden by Client Settings

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#58]
[The design document for FAPI-CIBA](https://github.com/keycloak/keycloak-community/blob/master/design/client-initiated-backchannel-authentication-flow.md#ciba-policy) states that it requires Realm Settings for CIBA called CIBA Policy and it can be overriden by each Client Setting.
 However, [the current CIBA prototype implementation](https://github.com/tnorimat/keycloak/tree/ciba-prototype) does not support the Client Setting for CIBA that can override the Realm Setting for CIBA.
 
The goal of this issue is to implement on the CIBA prototype implementation this override by following the design document for FAPI-CIBA.

**Comment by akoserwal** [comment]
@tnorimat: I can work on it

**Comment by VinodAnandan** [comment]
Thank you @akoserwal akoserwal

**Comment by tnorimat** [comment]
@akoserwal I've add the specification of this issues here.

### What to do

Current CIBA prototype implementation has already supported the following parameters CIBA standard document defined.

- Backchannel Token Delivery Mode
- Expires In
- Interval
- Authentication Requested User Hint

These parameters are realized as CIBA Policy that can be set per Realm.

What we want to do is that we can set these parameters also per Client.
If the above parameters are set on Client, ones set on Realm are ignored.
If not, parameters set on Realm are used.

These parameter settings' specification (eg. what value is accepted, initial value) per Client are the same as per Realm.

Codes of current CIBA prototype implementation referfing these parameters have to be modified to look at the parameter setting on Client at first.

### UI

On current client's "Settings" UI, new "CIBA Policy Overrides" pain is introduced like "Authentication Flow Overrides"

### Where to look if we  introduce new client setting 

AFAIK, entities we need to look at when we introduce new client setting are as follows.

- Representation
 It stands for the format in representating Client.
 This format is used when communicating between keycloak and other entities.
   - [1] ClientRepresentation
 It is Client's Representation.
 When we access Client by Admin REST API(namely, on Admin Console), this ClientRepresentation is used.

- Model
 It stands for the format used when keycloak's internal program treats Client.
  - [2]  ClientModel
 It is Client's Model

- Store
 It stands for the format used when keycloak's internal program stores Client.
   - Infinispan Cache
  Used when storing Client in memory
      - [3] ClientAdapter(infinispan)
   - JPA:
  Used when storing Client in persistent storage
      - [4] ClientAdapter(jpa)
      - [5] ClientEntity(jpa)

- OIDC Extension
 It extends Client so that it can be treated as OIDC conformant Client
   - Representation
     - [6] OIDCClientRepresentation
   It stands for the format in representating OIDC conformant Client.
   This format is used when communicating between keycloak and other entities in OIDC manner
   eg.
   When we access Client by OIDC Dynamic Client Registration, this OIDCClientRepresentation is used.

   - Representation/Model
      - [7] OIDCAdvancedConfigWrapper
    It works as the wrapper between ClientRepresentation and OIDCClientRepresentation
      - [8] DescriptionConverter
    It converts the Client representation between ClientRepresentation and OIDCClientRepresentation.
      - [9] OIDCConfigAttributes
     It define keys used to store/access OIDC related parameter to ClientRepresentation's map object called Attribute and ClientModel's map object also callled Attribute.

- UI
   - [10] client.js
   - [11] client-detail.html
   - [12] admin-messages_en.properties 

In this issue, we need not modify [3][4][5].

### Reference
The PRs about overriding per Realm settings by per Client settings are as follows :

- https://github.com/keycloak/keycloak/pull/6581
- https://github.com/keycloak/keycloak/pull/7065

**Comment by akoserwal** [comment]
@tnorimat thank you, for the information. I'll go over them and follow up with you If I face any issues.

**Comment by tnorimat** [comment]
I've merged @akoserwal 's work and taken over it to complete this feature by adding arquillian integration tests afterwards.

**Comment by tnorimat** [comment]
merged https://github.com/keycloak/keycloak/pull/7679 includes per client settings.
