### ISSUE TITLE
FAPI-CIBA Implementation Internals : Token Request Throttling Information Not Cluster-wide Sync

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#61]
[The design document for FAPI-CIBA](https://github.com/keycloak/keycloak-community/blob/master/design/client-initiated-backchannel-authentication-flow.md#token-request-throttling-1) states that it requires No.3 method for Token Request Throttling, namely keycloak does not share information on Token Request Throttling among other nodes in the cluster.
 However, [the current CIBA prototype implementation](https://github.com/tnorimat/keycloak/tree/ciba-prototype) employes No.2 method, namely keycloak shares information on Token Request Throttling among other nodes in the cluster.
 
 The goal of this issue is to modify the CIBA prototype implementation to use No.3 method for Token Request Throttling by following the design document for FAPI-CIBA.

**Comment by tnorimat** [comment]
IMO, it seems to be relatively easy compared with other FAPI-CIBA issues.

**Comment by andriimurashkin** [comment]
Please assign me this ticket.

**Comment by VinodAnandan** [comment]
Thank you @andriimurashkin

**Comment by andriimurashkin** [comment]
hi @tnorimat 
Could you please give some hint. 
Do I need extend CIBAAuthReqIdParser#parseAuthReqId section with `blocker.isNotFoundEarlyAccessBlocker()`?
Is there example "Use some collection with lifespan of its entry on each node"?

**Comment by tnorimat** [comment]
@andriimurashkin Hello,
I'll prepare the detailed information. Could you please wait for it for a while?

**Comment by tnorimat** [comment]
Current Token Request Throttling uses infinispan cache to share token request information among all nodes of the cluster.

In this issue, for Token Request Throttling, we use some store to hold token request information within this node, not sharing among all nodes of the cluster.

IMO, we can do the following steps.

1. Implement `CodeToTokenStoreProvider` for this purpose
   Currently, there is only one `CodeToTokenStoreProvider` implementation, namely `InfinispanCodeToTokenStoreProvider`.
   This implementation class can be used to share information among all nodes of the cluster.
   Instead of using it, we add new `CodeToTokenStoreProvider` implementation class like `OnNodeCodeToTokenStoreProvider`.
   This new provider needs to implement the store which satisfies the followings :
   - only one instance per keycloak node
   - support mutual exclusion

   As for realizing only one instance per keycloak node, the following ideas comes to me.
   - holding ConcurrentMap member for the instance representating keycloak itself
     IMO, it seems to be not good idea. This change might affects the basic part of the keycloak.
   - holding ConcurrentMap static member for the factory class, namely like `OnNodeCodeToTokenStoreProviderFactory`.
     In keycloak, there is only one instance of the factory while there are several instances of the provider created from its factory.
     The provider instances can refer to this static member of their factory class.

   For example, in `keycloak-services` projects,
   - Implement provider/provider factory
     on `org.keycloak.protocol.ciba.store` package, implement `OnNodeCodeToTokenStoreProvider` and `OnNodeCodeToTokenStoreProviderFactory`.
   - Register provider/provider factory to keycloak
     in `src/main/resources/META-INF/services/` , create `org.keycloak.models.CodeToTokenStoreProvider` file including
     `org.keycloak.protocol.ciba.store.OnNodeCodeToTokenStoreProviderFactory`

2. Use this store for Token Request Throttling
   In `EarlyAccessBlockerParser.persistEarlyAccessBlocker` ,
   ```
         CodeToTokenStoreProvider codeStore = session.getProvider(CodeToTokenStoreProvider.class, OnNodeCodeToTokenStoreProviderFactory.PROVIDER_ID);
   ```
   instead of the current codes :
   ```
         CodeToTokenStoreProvider codeStore = session.getProvider(CodeToTokenStoreProvider.class);
   ```
   keycloak has the mechanism of instanciate the specifc provider by specifying its factory ID.
   `OnNodeCodeToTokenStoreProviderFactory.PROVIDER_ID` stands for it.

3. Modify existing codes instanciating `CodeToTokenStoreProvider`
   Current keycloak's codes assume that there is only one implementation provider class for `CodeToTokenStoreProvider`, namely `InfinispanCodeToTokenStoreProvider`.
   However, by introducing another provider like `OnNodeCodeToTokenStoreProviderFactory`, this assumption becomes not satisfied.
   Therefore, we need to modify such codes to instantiate provider by specifying its factory explicitly.
   For example, in `OAuth2CodeParser.persistCode`,
   ```
        CodeToTokenStoreProvider codeStore = session.getProvider(CodeToTokenStoreProvider.class, InfinispanCodeToTokenStoreProviderFactory.PROVIDER_ID);
   ```
   instead of the current codes :
   ```
           CodeToTokenStoreProvider codeStore = session.getProvider(CodeToTokenStoreProvider.class);
   ```
   Also, the current `InfinispanCodeToTokenStoreProviderFactory` does not have a static member showing its provider id. Therefore, we need to implement it.

I've not yet confirmed that this works well. That's just an idea.

**Comment by tnorimat** [comment]
merged. https://github.com/tnorimat/keycloak/pull/10

**Comment by bfyxzls** [comment]
@tnorimat hello,I have infinispan server cluster(192.168.1.1,192.168.1.2,192.168.1.3),then my keycloak server have tow nodes,I find a problem,when I get login page and submit login then occur errors,it means that get login generate code in node1,submit login in node2,however node2 have not this code .(because this code in node1)

**Comment by tnorimat** [comment]
Hello @bfyxzls ,
Have you used CIBA when you've encountered this issue? Or used ordinal authorization code flow?
If the latter, it seems that it is not relevant to CIBA and It might be better to ask it for [keycloak](https://github.com/keycloak/keycloak).
