### ISSUE TITLE
FAPI-CIBA Implementation Internals : Use Security Event Token (SET) as message format between keycloak and Decoupled Auth Server

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#62]
[The design document for FAPI-CIBA](https://github.com/keycloak/keycloak-community/blob/master/design/client-initiated-backchannel-authentication-flow.md#default-implementation-of-authnauthz-by-ad-part-of-outside-ciba-protocol) states that it requires application/x-www-form-urlencoded form data as message format between keycloak and Decoupled Auth Server.
 
 It might be preferable to use [Security Event Token (SET)](https://tools.ietf.org/html/rfc8417) instead of it.

**Comment by tnorimat** [comment]
IMO, this issue's priority is relatively low compared with other FAPI-CIBA issues.

**Comment by tnorimat** [comment]
Considering Security Event Token's nature (it is used to inform security related facts that have already happened), it seems not to be appropriate to use SET as the message between keycloak and Decoupled Auth Server.
Therefore, it is simply based on JWT claims.

**Comment by HryhoriiHevorkian** [comment]
Please assign this task for me.

**Comment by tnorimat** [comment]
@HryhoriiHevorkian

Please refer to the page 17 of [CIBA prototype implementation practical guide](https://github.com/keycloak/kc-sig-fapi/blob/master/FAPI-SIG/documents/FAPI-CIBA/CIBA_PrototypeImplPracticalGuide.pdf). We need to support JWT formatted requests(REQ-2 and REQ-3 of the sequence). 

In this issue, we need to do the followings :

- Support JWT formatted request REQ-2 from keycloak to Decoupled Auth Server
  Please refer to the page 28 of [CIBA prototype implementation practical guide](https://github.com/keycloak/kc-sig-fapi/blob/master/FAPI-SIG/documents/FAPI-CIBA/CIBA_PrototypeImplPracticalGuide.pdf). 
  We need to change the form format defined in this page to JWT format as follows :
  - "iss" (Issuer) Claim
     It shows keycloak itself. It is the same as "iss" of Access Token, Refresh Token and ID Token.
  - "iat" (Issued At) Claim
     It shows when this request is created.
  - "jti" (JWT ID) Claim
     It shows this request's ID. It can be created by the same manner as Access Token, Refresh Token and ID Token.
  - "aud" (Audience) Claim
     It shows to which this request is sent. In this prototype implementation, Decoupled Auth Server needs to be registered to keycloak as Confidential Client. Therefore, we set its "client_id" to this "aud" claim.
  - "sub" (Subject) Claim
     It show who will be authenticated(AuthN) and authorized(AuthZ) by Authentication Device(AD). 
     We set "user_info" form item in page 28 to this "user_info" claim.
  - "exp" (Expiration Time) Claim
     It shows when this request expires. We set Backchannel Authentication Request(REQ-1)'s "expires_in" to this "exp" claim.
  - "decoupled_auth_id" Claim
     We set "decoupled_auth_id" form item in page 28 to this "decoupled_auth_id" claim.
  - "scope" Claim
     We set "scope" form item in page 28 to this "scope" claim.
  - "is_consent_required" Claim
     We set "is_consent_required" form item in page 28 to this "is_consent_required" claim. This claim's value type is boolean.
  - "default_client_scope" Claim
     We set "default_client_scope" form item in page 28 to this "default_client_scope" claim.
  - "binding_message" Claim
     We set "binding_message" form item in page 28 to this "binding_message" claim.
- Support JWT formatted request REQ-3 from Decoupled Auth Server to keycloak
  Please refer to the page 31 of [CIBA prototype implementation practical guide](https://github.com/keycloak/kc-sig-fapi/blob/master/FAPI-SIG/documents/FAPI-CIBA/CIBA_PrototypeImplPracticalGuide.pdf). 
  We need to change the form format defined in this page to JWT format as follows :
  - "iss" (Issuer) Claim
     It shows Decoupled Auth Server. In this prototype implementation, Decoupled Auth Server needs to be registered to keycloak as Confidential Client. Therefore, we set its "client_id" to this "iss" claim.
  - "iat" (Issued At) Claim
     It shows when this request is created.
  - "jti" (JWT ID) Claim
     It shows this request's ID. It can be created by the same manner as keycloak generating Access Token, Refresh Token and ID Token.
  - "aud" (Audience) Claim
     It shows to which this request is sent, namely keycloak.  It is the same as "iss" of keycloak generating Access Token, Refresh Token and ID Token.
  - "sub" (Subject) Claim
     It show who was authenticated(AuthN) and authorized(AuthZ) by Authentication Device(AD). 
     We set "user_info" form item in page 31 to this "user_info" claim.
  - "decoupled_auth_id" Claim
     We set "decoupled_auth_id" form item in page 31 to this "decoupled_auth_id" claim.
  - "auth_result" Claim
     We set "auth_result" form item in page 31 to this "auth_result" claim.

We need to modify codes not only keycloak itself but Decoupled Auth Server Reference Implementation([ciba-decoupled-authn-server](https://github.com/tnorimat/ciba-decoupled-authn-server)).

**Comment by tnorimat** [comment]
merged. https://github.com/tnorimat/keycloak/pull/12
