### ISSUE TITLE
 FAPI-CIBA Arquillian Integration Test : Confirm CIBA Implementation Works Well in Cross-DC Environment

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#64]
[The design document for FAPI-CIBA](https://github.com/keycloak/keycloak-community/blob/master/design/client-initiated-backchannel-authentication-flow.md#runtime-environment) states that it requires keycloak to run well in the Cross-DC environment.
 However, [the current CIBA prototype implementation](https://github.com/tnorimat/keycloak/tree/ciba-prototype) does not have the arquillian integration test for CIBA support in the Cross-DC environment.
 
 The goal of this issue is to write the arquillian integration test for CIBA support in the Cross-DC environment and confirms that it works well.

**Comment by kannan-ra** [comment]
you can assign to @arunganesh-a (banfico)

**Comment by tnorimat** [comment]
@kannan-ra Thank you very much.
@VinodAnandan We would like to assign @arunganesh-a this issue. WDYT?

**Comment by VinodAnandan** [comment]
@arunganesh-a could you please write comments on this issue?

**Comment by arunganesh-a** [comment]
@VinodAnandan  you can assign it to me

**Comment by VinodAnandan** [comment]
Thank you @arunganesh-a

**Comment by tnorimat** [comment]
@arunganesh-a Hello. Thank you for your contribution on this issue.

On releasing the new version of keycloak (12.0.1), I've upgraded the keycloak used on this FAPI-SIG's FAPI-RW conformance test environment from 11.0.1 to 12.0.1. After that, I've run the automated conformance test by `docker-compose up --build` and confirmed that all FAPI-RW conformance tests have been passed against this keycloak version.

Therefore, would you mind if I could close this issue?

**Comment by arunganesh-a** [comment]
@tnorimat  Sure we can close the issue

**Comment by tnorimat** [comment]
@arunganesh-a I'm sorry. I've post the comment by mistake. Could you refer to https://github.com/keycloak/kc-sig-fapi/issues/40 ?

**Comment by tnorimat** [comment]
not planned, thank you.
