### ISSUE TITLE
FAPI-CIBA Conformance Test : Establish the way of running FAPI-CIBA OP poll w/ MTLS and w/ Private Key against CIBA Implementation

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#65]
Theoretically, we can run both conformance tests of FAPI-CIBA OP poll w/ MTLS and w/ Private Key against [the current CIBA prototype implementation](https://github.com/tnorimat/keycloak/tree/ciba-prototype). Of course, cannot pass all tests.
 
The goal of this issue is to establish how to run both conformance tests of FAPI-CIBA OP poll w/ MTLS and w/ Private Key against [the current CIBA prototype implementation](https://github.com/tnorimat/keycloak/tree/ciba-prototype) and contribute it to [keycloak-fapi](https://github.com/jsoss-sig/keycloak-fapi) in order for others to run it.

**Comment by kannan-ra** [comment]
Banfico will be able to help on this - you can assign to @arunganesh-a

**Comment by tnorimat** [comment]
@kannan-ra Thank you very much.
@VinodAnandan We would like to assign @arunganesh-a this issue. WDYT?

**Comment by VinodAnandan** [comment]
@tnorimat yes, I will assign to @arunganesh-a

**Comment by tnorimat** [comment]
To assign @arunganesh-a to this issue, @arunganesh-a needs to write some comments on this issue.
@arunganesh-a, could you please write some comments on this issue?

**Comment by arunganesh-a** [comment]
Hi @tnorimat  you can assign it to me..

**Comment by tnorimat** [comment]
@VinodAnandan Could you assign @arunganesh-a to this issue?

**Comment by VinodAnandan** [comment]
@tnorimat @arunganesh-a done :)

**Comment by tnorimat** [comment]
We can run FAPI-CIBA conformance test against keycloak 13 but tests almost fail.

To run tests and get reasonable results, the following needs to be done.

- Client setting on keycloak for CIBA
- Prepare an authentication entity
- Keycloak server setting for CIBA

### Client setting on keycloak for CIBA

#### CIBA Grant Enabled

As [Server Administrator Guide](https://www.keycloak.org/docs/latest/server_admin/index.html#oidc-clients) mentioned, there is a flag showing whether CIBA is enabled on a client.

In this FAPI-SIG's automated testing environment, a client settings can be provided as `realm.json` realm setting file.
Therefore, we need to add this setting as client attribute to clients that tests use like
```
             "attributes": {
                 "x509.subjectdn": "CN=client1, OU=Keycloak-fapi, O=Secure OSS Sig, ST=Client, C=JP",
                 "request.object.signature.alg": "PS256",
+                "oidc.ciba.grant.enabled": "true",
...
```

#### CIBA Backchannel Token Delivery Mode

As [Server Administrator Guide](https://www.keycloak.org/docs/latest/server_admin/index.html#oidc-clients) did not mentioned, there is a flag showing which CIBA backchannel token delivery mode is used. Current keycloak only accepts "poll" so that we need to add this setting as client attribute to clients that tests use  in `realm.json` like
```
             "attributes": {
                 "x509.subjectdn": "CN=client1, OU=Keycloak-fapi, O=Secure OSS Sig, ST=Client, C=JP",
                 "request.object.signature.alg": "PS256",
+                "ciba.backchannel.token.delivery.mode": "poll",
...
```

#### CIBA Signed Authentication Request Signature Algorithm

CIBA defines signed authentication requests. The current keycloak has not yet supported but its [PR](https://github.com/keycloak/keycloak/pull/8006) has been submitted.

If we use the keycloak after the PR above is merged, or if we use the keycloak incorporating this PR on local branch because we do not wait for the PR above being merged, we need to add this setting as client attribute to clients that tests use  in `realm.json` like
```
             "attributes": {
                 "x509.subjectdn": "CN=client1, OU=Keycloak-fapi, O=Secure OSS Sig, ST=Client, C=JP",
                 "request.object.signature.alg": "PS256",
+                "ciba.backchannel.auth.request.signing.alg": "PS256",
...
```
Make sure that this algorithm should be PS256, PS384, PS512, ES256, ES384 or ES512.

### Prepare an authentication entity

As [Server Administration Guide](https://www.keycloak.org/docs/latest/server_admin/index.html#authentication-channel-provider) described, keycloak delegate user authentication itself to other entity called "authentication entity".

keycloak abstracts the communication between itself and the authentication entity as "authentication channel".

keycloak defines the protocol on the authentication channel. [Server Administration Guide](https://www.keycloak.org/docs/latest/server_admin/index.html#authentication-channel-provider) also described it.

Therefore, we need to prepare the authentication entity that can speak the protocol on the authentication channel in this FAPI-SIG automated testing environment.

It might be helpful to refer to `client_private_keys` implementation because both `authentication_entity` and `client_private_keys` can only speaks to keycloak in backchannel while other server component in this environmen like `resource_server` can also speaks to clients that are simulated by conformance-suite.
 
### Keycloak server setting for CIBA

As [Server Administration Guide](https://www.keycloak.org/docs/latest/server_admin/index.html#provider-setting) described, keycloak needs to know the authentication entity's configuration.

```
<spi name="ciba-auth-channel">
    <default-provider>ciba-http-auth-channel</default-provider>
    <provider name="ciba-http-auth-channel" enabled="true">
        <properties>
            <property name="httpAuthenticationChannelUri" value="https://backend.internal.example.com/auth"/>
        </properties>
    </provider>
</spi>
```

We can write the authentication entity's URL as value of property "httpAuthenticationChannelUri". 

To do so, we can modify wildfly's setting file like `standalone.xml` or putting CLI command to keycloak before running tests.
