### ISSUE TITLE
Client Policy : Pre-set Policies

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#76]
This issue is about [KEYCLOAK-14208 Client Policy : Pre-set Policies](https://issues.redhat.com/browse/KEYCLOAK-14208) in [KEYCLOAK-13933 Client Policies](https://issues.redhat.com/browse/KEYCLOAK-13933).

The goal of this project are the followings.
- support pre-set client policy defined in [Client Policy design document](https://github.com/keycloak/keycloak-community/blob/master/design/client-policies.md#pre-set-policy)

What pre-set client policies need to do are what need to be done by all means on each endpoint like Authorization Endpoint, Token Endpoint (eg. parsing and verifying the request from the client).

**Comment by HryhoriiHevorkian** [comment]
Hello, @VinodAnandan ! Please assign this task for me.

**Comment by HryhoriiHevorkian** [comment]
@tnorimat Please, provide some details for implementing this task.

**Comment by tnorimat** [comment]
@HryhoriiHevorkian Hello.

Generally speaking, the pre-set policy is the one that can not be modified and deleted by anyone even if by keycloak administrator.

Currently, the detailed specification has not yet determined (eg. discussed in https://github.com/keycloak/keycloak-community/pull/188), Hopefully you would you wait for deterimning it.

**Comment by tnorimat** [comment]
In progress. It will be supported by keycloak 14.

- Ticket : [KEYCLOAK-14208 Client Policy : Pre-set Policies (including FAPI preset policies)](https://issues.redhat.com/browse/KEYCLOAK-14208)
- ML : [Default client profiles for FAPI](https://groups.google.com/g/keycloak-dev/c/Hyzib1Tm3zY)
- PR : not yet
