### ISSUE TITLE
Client Policy : Migrate Client Registration Policies to Client Policies​

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#78]
This issue is about [KEYCLOAK-14210 Client Policy : Migrate Client Registration Policies to Client Policies](https://issues.redhat.com/browse/KEYCLOAK-14210) in [KEYCLOAK-13933 Client Policies](https://issues.redhat.com/browse/KEYCLOAK-13933).

The goal of this project are the followings.
- Support Backward Compatibility defined in [Client Policy design document](https://github.com/keycloak/keycloak-community/blob/master/design/client-policies.md#backward-compatibility)

Currently, there are 2 options for realizing it.

- migrate existing Client Registration Policy completely
- allow both Client Policy and Client Registration Policy to be co-exist

We've not yet determine which option to be taken. In the latter case, we can defer this issue.

**Comment by andriimurashkin** [comment]
Hi @VinodAnandan 
Please assign this task to me.

**Comment by VinodAnandan** [comment]
Done. Thank you @andriimurashkin

**Comment by andriimurashkin** [comment]
@tnorimat 
Could you please give some background and details?

Thanks in advance.

**Comment by tnorimat** [comment]
@andriimurashkin Hello.
The goal of this issue are as follows.

- Implement the client policies' executors that do the same thing done by the existing following 7 client registration policies.
  - `ClientDisabledClientRegistrationPolicy`
  - `ClientScopesClientRegistrationPolicy`
  - `ConsentRequiredClientRegistrationPolicy`
  - `MaxClientsClientRegistrationPolicy`
  - `ProtocolMappersClientRegistrationPolicy`
  - `ScopeClientRegistrationPolicy`
  - `TrustedHostClientRegistrationPolicy`

- Implemented client policies' executors need to pass tests equivalent to all existing client policies' tests implemented in `ClientRegistrationPoliciesTest`.

However, there is the issue need to be resolved in advance.

The existing client registration policies are called when the following event happens.
  - Before registering a client
  - After registering a client
  - Before updating a client
  - After updating a client
  - Before viewing a client's settings
  - Before deleting a client

Among these events, the client policies are called when the following event happens.
  - Before registering a client
  - Before updating a client

Therefore, the client policies are NOT called when the following event happens.
  - After registering a client
  - After updating a client
  - Before viewing a client's settings
  - Before deleting a client

We need to modify the client policies to be called on when these event happens.

We've already worked on this issue.

JIRA ticket :
https://issues.redhat.com/browse/KEYCLOAK-15533

github issue :
https://github.com/keycloak/kc-sig-fapi/issues/79

branch (WIP) :
https://github.com/tnorimat/keycloak/tree/WIP-KEYCLOAK-15533


In principle, after resolving this issue, we can start the implementation of the client policies.

JIRA ticket :
https://issues.redhat.com/browse/KEYCLOAK-15534

github issue :
https://github.com/keycloak/kc-sig-fapi/issues/80

branch (WIP) :
https://github.com/tnorimat/keycloak/tree/WIP-KEYCLOAK-15534


However, considering the nature of each client registration policies, we can partially start working on the implementation of client policies for the existing client registratin policy which is NOT called when the following event happens.
  - After registering a client
  - After updating a client
  - Before viewing a client's settings
  - Before deleting a client

The characteristics of each client registration policy are shown below.

[1] ClientDisabledClientRegistrationPolicy
  - Before registering a client
    Not Called
  - Before updating a client
    Called
  - After registering a client
    Called
  - After updating a client
    Not Called
  - Before viewing a client's settings
    Not Called
  - Before deleting a client
    Not Called

[2] ClientScopesClientRegistrationPolicy
  - Before registering a client
    Called
  - Before updating a client
    Called
  - After registering a client
    Not Called
  - After updating a client
    Not Called
  - Before viewing a client's settings
    Not Called
  - Before deleting a client
    Not Called

[3] ConsentRequiredClientRegistrationPolicy
  - Before registering a client
    Not Called
  - Before updating a client
    Called
  - After registering a client
    Called
  - After updating a client
    Not Called
  - Before viewing a client's settings
    Not Called
  - Before deleting a client
    Not Called

[4] MaxClientsClientRegistrationPolicy
  - Before registering a client
    Called
  - Before updating a client
    Not Called
  - After registering a client
    Not Called
  - After updating a client
    Not Called
  - Before viewing a client's settings
    Not Called
  - Before deleting a client
    Not Called

[5] ProtocolMappersClientRegistrationPolicy
  - Before registering a client
    Called
  - Before updating a client
    Called
  - After registering a client
    Called
  - After updating a client
    Not Called
  - Before viewing a client's settings
    Not Called
  - Before deleting a client
    Not Called

[6] ScopeClientRegistrationPolicy
  - Before registering a client
    Not Called
  - Before updating a client
    Called
  - After registering a client
    Called
  - After updating a client
    Not Called
  - Before viewing a client's settings
    Not Called
  - Before deleting a client
    Not Called

[7] TrustedHostClientRegistrationPolicy
  - Before registering a client
    Called
  - Before updating a client
    Called
  - After registering a client
    Not Called
  - After updating a client
    Not Called
  - Before viewing a client's settings
    Called
  - Before deleting a client
    Called

Considering these characteristics, we can start working on the implementation of the executor for the following client registration policies.

- [2] ClientScopesClientRegistrationPolicy
- [4] MaxClientsClientRegistrationPolicy

Therefore, you could choose the following options.

- Implement the executor for the client registration policies `ClientScopesClientRegistrationPolicy` and `MaxClientsClientRegistrationPolicy`.
- Take over https://github.com/keycloak/kc-sig-fapi/issues/79.

**Comment by andriimurashkin** [comment]
Hi @tnorimat 
I've implemented first part and added executors for the client registration policies `ClientScopesClientRegistrationPolicy` and `MaxClientsClientRegistrationPolicy`.
https://github.com/tnorimat/keycloak/pull/17

but I have some concerns about:
1. method getClientByAdmin does not return stored scopes (see test `testClientScopesClientRegistrationEnforcerExecutor` commented lines) 
2. How should I migrate the other clientRegistryPolicies with events ...before and ...after? Do I need to create events, like this 
```
beforeRegister -> REGISTER 
afterRegister -> POST_REGISTER
```

**Comment by tnorimat** [comment]
@andriimurashkin Thank you. I'll look into https://github.com/tnorimat/keycloak/pull/17.

As for 1, I might also expect that we can not treat scopes on `getClientByAdmin` because the concept of "scope" is defined by OAuth2.0/OIDC. Basically we can not specify and get the ones based on these concept via Admin REST API. However, we might get ones based on these concept by specifying Attribute. I'll investigate which "Attribute" corresponds with "scope".
 
As for 2, could you please refer  to https://github.com/keycloak/kc-sig-fapi/issues/79 ? @HryhoriiHevorkian tries to resolve it.

**Comment by tnorimat** [comment]
merged. https://github.com/tnorimat/keycloak/pull/18

**Comment by tnorimat** [comment]
I'll close after send this PR to keycloak upstream and is merged.
