### ISSUE TITLE
Client Policy : Extends Policy Interface to Migrate Client Registration Policies

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#79]
This issue is about [KEYCLOAK-15533 Client Policy : Extends Policy Interface to Migrate Client Registration Policies](https://issues.redhat.com/browse/KEYCLOAK-15533) in [KEYCLOAK-13933 Client Policies](https://issues.redhat.com/browse/KEYCLOAK-13933).

This issue is the sub issue of https://github.com/keycloak/kc-sig-fapi/issues/78 .

The goal of this project are the followings.
- extends the current interfaces of `ClientPolicyConditionProvider` and `ClientPolicyExecutorProvider` to realize existing all 7 Client Registration Policy's providers.

As mentioned in https://github.com/keycloak/kc-sig-fapi/issues/78, currently, there are 2 options for realizing it.

- migrate existing Client Registration Policy completely
- allow both Client Policy and Client Registration Policy to be co-exist

We've not yet determine which option to be taken. In the latter case, we can defer this issue.

**Comment by HryhoriiHevorkian** [comment]
Hello, @tnorimat Please, assign this task to me.

**Comment by tnorimat** [comment]
@HryhoriiHevorkian Hello. When you start the issue, could you please at first ask @VinodAnandan ?

**Comment by HryhoriiHevorkian** [comment]
Hello, @VinodAnandan . Could you please assign this issue to me?

**Comment by VinodAnandan** [comment]
Thank you @HryhoriiHevorkian

**Comment by HryhoriiHevorkian** [comment]
Hello, @tnorimat . After investigating this task, I have realized that we have no events, for example, for client deletion (I mean the enumerator `ClientPolicyEvent`). Should I add this event?

Another problem with the old events, which have 2 cases: before and after. But new events have only one case. How should I map the old ones to the new ones? Do you have any plan for this migration, otherwise we are getting blocked with this issue? Thank you!

**Comment by tnorimat** [comment]
@HryhoriiHevorkian Hello. We need to add new events to `ClientPolicyEvent`. The situation around it has been describled in https://github.com/keycloak/kc-sig-fapi/issues/78#issuecomment-735517976.
I've partially realized this issue on https://github.com/tnorimat/keycloak/tree/WIP-KEYCLOAK-15533 . It might be helpful for you. If you have some question on it, please feel free to ask me.

**Comment by HryhoriiHevorkian** [comment]
@tnorimat Hello, Takashi. Could you please check this PR to verify that I'm going in the correct direction? https://github.com/tnorimat/keycloak/pull/18

**Comment by tnorimat** [comment]
@HryhoriiHevorkian Thank you. I'll look into https://github.com/tnorimat/keycloak/pull/18.

**Comment by tnorimat** [comment]
merged. https://github.com/tnorimat/keycloak/pull/18
