### ISSUE TITLE
Client Policy - Condition : Client - Client Domain Name

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#84]
This issue is about [KEYCLOAK-14194 Client Policy - Condition : Client - Client Domain Name](https://issues.redhat.com/browse/KEYCLOAK-14194) in [KEYCLOAK-13933 Client Policies](https://issues.redhat.com/browse/KEYCLOAK-13933).

The goal of this project are the followings.
- support policy conditions defined in [Client Policy design document](https://github.com/keycloak/keycloak-community/blob/master/design/client-policies.md#which-kind-of-conditions-are-provided)

The support detail can be found its [JIRA ticket](https://issues.redhat.com/browse/KEYCLOAK-14194).

**Comment by DmitryMishchuk** [comment]
Could be assigned to me.
Regards.

**Comment by VinodAnandan** [comment]
@DmitryMishchuk thank you !

**Comment by tnorimat** [comment]
According to the discussion in https://github.com/keycloak/keycloak/pull/7628, This Client Domain Condition is incorporated into the Client Host Condition. The Client Domain Condition is implemented as part of the Client Host Condition. Therefore, this Client Domain Condition PR needs not to be sent to keycloak individually.

If https://github.com/keycloak/kc-sig-fapi/issues/86 is resolved, this issue is also resolved.

**Comment by tnorimat** [comment]
resolved by https://github.com/keycloak/keycloak/pull/7628
