### ISSUE TITLE
Client Policy - Executor : Enforce Holder-of-Key Token

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#89]
This issue is about [KEYCLOAK-14200 Client Policy - Executor : Enforce Holder-of-Key Token](https://issues.redhat.com/browse/KEYCLOAK-14200) in [KEYCLOAK-13933 Client Policies](https://issues.redhat.com/browse/KEYCLOAK-13933).

The goal of this project are the followings.
- support policy executors defined in [Client Policy design document](https://github.com/keycloak/keycloak-community/blob/master/design/client-policies.md#which-kind-of-executors-are-provided)

The support detail can be found its [JIRA ticket](https://issues.redhat.com/browse/KEYCLOAK-14200).

**Comment by HryhoriiHevorkian** [comment]
Hello, @tnorimat , please assign this task to me. Thanks :)

**Comment by VinodAnandan** [comment]
Thank you @HryhoriiHevorkian

**Comment by HryhoriiHevorkian** [comment]
Hello, @tnorimat . Could you please clarify a little bit with this ticket? I have already created the factory, registered it and created an executor: https://github.com/tnorimat/keycloak/pull/15

Next, in my opinion, I have to implement some kind of checking for "cnf" secret field with the client fingerprint - am I right?

**Comment by tnorimat** [comment]
@HryhoriiHevorkian Hello.
Sorry for the inconvenient due to lacking of enough information.

This executor needs to do the following works on each `ClientPolicyEvent`.
- check/enforce client settings
  - `REGISTER`
  - `UPDATE`
- check incoming requests and refuse them if needed
  - `TOKEN_REQUEST`
  - `TOKEN_REFRESH`
  - `TOKEN_REVOKE`
  - `USERINFO_REQUEST`
  - `LOGOUT_REQUEST`

### check/enforce client settings
The check and enforce process can be realized by `AbstractAugumentingClientRegistrationPolicyExecutor`. You can extend it and implement `augment()` and `validate()`.
It might be helpful for you to refer to `PKCEEnforceExecutor`.

On `augment()`, you can enforce Holder-of-Token usage against the client by using the following methods.
```
OIDCAdvancedConfigWrapper.fromClientRepresentation(ClientRepresentation rep).setUseMtlsHoKToken(boolean useUtlsHokToken)
```

On `validate()`, you can check Holder-of-Token usage against the client by using the following methods.

```
OIDCAdvancedConfigWrapper.fromClientRepresentation(ClientRepresentation rep).isUseMtlsHokToken()
```

### check incoming requests and refuse them if needed

#### `TOKEN_REQUEST`
You need to check the following point.

If the Holder-of-Token usage is active against the client and this client did not send its certificate, the executor needs to return the error.

This specification of the error response needs to be the same as the current implementation treating this certificate check on  
https://github.com/keycloak/keycloak/blob/da186af13d137f6ba7604b685cc8d0df3382494d/services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java#L447

Therefore, the executor informs the error by `ClientPolicyException`. Its `.getErrorDetail()` must be `"Client Certification missing for MTLS HoK Token Binding"`

#### `TOKEN_REFRESH`
You need to check the following point.

- The client did not send its certificate, the executor needs to return the error.

- The client send its certificate but the refresh token's "cnf" does not match this certificates fingerprint exactly, the executor needs to return the error.
  You can use `MtlsHoKTokenUtil.verifyTokenBindingWithClientCertificate`.
  This specification of the error response of the two cases just above needs to be the same as the current implementation treating this certificate check on
https://github.com/keycloak/keycloak/blob/da186af13d137f6ba7604b685cc8d0df3382494d/services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java#L560
  However, it can not be achieved by only appropriate setting for `ClientPolicyException` . We need to modify the existing `TokenEndpoint`.
  Wrap up them, we need to do the followings.
  - `ClientPolicyException.getError()` needs to be `Errors.NOT_ALLOWED`.
  - `ClientPolicyException.getErrorDetail()` needs to be `MtlsHoKTokenUtil.CERT_VERIFY_ERROR_DESC`.
  - `TokenEndpoint.refreshTokenGrant()`'s the current client policy related following codes
```
        try {
            session.clientPolicy().triggerOnEvent(new TokenRefreshContext(formParams));
        } catch (ClientPolicyException cpe) {
            event.error(cpe.getError());
            throw new CorsErrorResponseException(cors, OAuthErrorException.INVALID_GRANT, cpe.getErrorDetail(), Response.Status.BAD_REQUEST);
        }
```
might be modified as follows.

```
        try {
            session.clientPolicy().triggerOnEvent(new TokenRefreshContext(formParams));
        } catch (ClientPolicyException cpe) {
            event.error(cpe.getError());
            if (MtlsHoKTokenUtil.CERT_VERIFY_ERROR_DESC.equals(cpe.getErrorDetail())) {
                throw new CorsErrorResponseException(cors, e.getError(), e.getErrorDetail(), Response.Status.UNAUTHORIZED);
            }
            throw new CorsErrorResponseException(cors, OAuthErrorException.INVALID_GRANT, cpe.getErrorDetail(), Response.Status.BAD_REQUEST);
        }
```


#### `TOKEN_REVOKE`
Generally speaking, you need to do the almost same thing as in `TOKEN_REFRESH`.

You need to check the following point.

- The client did not send its certificate, the executor needs to return the error.

- The client send its certificate but the refresh token's "cnf" does not match this certificates fingerprint exactly, the executor needs to return the error.

  You can use `MtlsHoKTokenUtil.verifyTokenBindingWithClientCertificate`.
  This specification of the error response of the two cases just above needs to be the same as the current implementation treating this certificate check on
https://github.com/keycloak/keycloak/blob/da186af13d137f6ba7604b685cc8d0df3382494d/services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java#L560
  However, it can not be achieved by only appropriate setting for `ClientPolicyException` . We need to modify the existing `TokenRevocationEndpoint`.
  Wrap up them, we need to do the followings.
  - `ClientPolicyException.getError()` needs to be `Errors.NOT_ALLOWED`.
  - `ClientPolicyException.getErrorDetail()` needs to be `MtlsHoKTokenUtil.CERT_VERIFY_ERROR_DESC`.
  - `TokenRevocationEndpoint.revoke()`'s the current client policy related following codes
```
        try {
            session.clientPolicy().triggerOnEvent(new TokenRevokeContext(formParams));
        } catch (ClientPolicyException cpe) {
            event.error(cpe.getError());
            throw new CorsErrorResponseException(cors, OAuthErrorException.INVALID_GRANT, cpe.getErrorDetail(), Response.Status.BAD_REQUEST);
        }
```
might be modified as follows.

```
        try {
            session.clientPolicy().triggerOnEvent(new TokenRevokeContext(formParams));
        } catch (ClientPolicyException cpe) {
            event.error(cpe.getError());
            if (MtlsHoKTokenUtil.CERT_VERIFY_ERROR_DESC.equals(cpe.getErrorDetail())) {
                throw new CorsErrorResponseException(cors, e.getError(), e.getErrorDetail(), Response.Status.UNAUTHORIZED);
            }
            throw new CorsErrorResponseException(cors, OAuthErrorException.INVALID_GRANT, cpe.getErrorDetail(), Response.Status.BAD_REQUEST);
        }
```

#### `USERINFO_REQUEST`
Generally speaking, you need to do the almost same thing as in `TOKEN_REFRESH` except for treating an access token.

You need to check the following point.

- The client did not send its certificate, the executor needs to return the error.

- The client send its certificate but the access token's "cnf" does not match this certificates fingerprint exactly, the executor needs to return the error.

  You can use `MtlsHoKTokenUtil.verifyTokenBindingWithClientCertificate`.
  This specification of the error response of the two cases just above needs to be the same as the current implementation treating this certificate check on
https://github.com/keycloak/keycloak/blob/da186af13d137f6ba7604b685cc8d0df3382494d/services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java#L560
  However, it can not be achieved by only appropriate setting for `ClientPolicyException` . We need to modify the existing `UserInfoEndpoint`.
  Wrap up them, we need to do the followings.
  - `ClientPolicyException.getError()` needs to be `Errors.NOT_ALLOWED`.
  - `ClientPolicyException.getErrorDetail()` needs to be `MtlsHoKTokenUtil.CERT_VERIFY_ERROR_DESC`.
  - `UserInfoEndpoint.issueUserInfo()`'s the current client policy related following codes
```
        try {
            session.clientPolicy().triggerOnEvent(new UserInfoRequestContext(tokenString));
        } catch (ClientPolicyException cpe) {
            throw new ErrorResponseException(Errors.INVALID_REQUEST, cpe.getErrorDetail(), Response.Status.BAD_REQUEST);
        }
```
might be modified as follows.

```
        try {
            session.clientPolicy().triggerOnEvent(new UserInfoRequestContext(tokenString));
        } catch (ClientPolicyException cpe) {
            if (MtlsHoKTokenUtil.CERT_VERIFY_ERROR_DESC.equals(cpe.getErrorDetail())) {
                throw new ErrorResponseException(e.getError(), e.getErrorDetail(), Response.Status.UNAUTHORIZED);
            }
            throw new ErrorResponseException(Errors.INVALID_REQUEST, cpe.getErrorDetail(), Response.Status.BAD_REQUEST);
        }
```

#### `LOGOUT_REQUEST`
Generally speaking, you need to do the almost same thing as in `TOKEN_REFRESH`.

You need to check the following point.

- The client did not send its certificate, the executor needs to return the error.

- The client send its certificate but the refresh token's "cnf" does not match this certificates fingerprint exactly, the executor needs to return the error.

  You can use `MtlsHoKTokenUtil.verifyTokenBindingWithClientCertificate`.
  This specification of the error response of the two cases just above needs to be the same as the current implementation treating this certificate check on
https://github.com/keycloak/keycloak/blob/da186af13d137f6ba7604b685cc8d0df3382494d/services/src/main/java/org/keycloak/protocol/oidc/endpoints/TokenEndpoint.java#L560
  However, it can not be achieved by only appropriate setting for `ClientPolicyException` . We need to modify the existing `LogoutEndpoint`.
  Wrap up them, we need to do the followings.
  - `ClientPolicyException.getError()` needs to be `Errors.NOT_ALLOWED`.
  - `ClientPolicyException.getErrorDetail()` needs to be `MtlsHoKTokenUtil.CERT_VERIFY_ERROR_DESC`.
  - `LogoutEndpoint.logoutToken()`'s the current client policy related following codes
```
        try {
            session.clientPolicy().triggerOnEvent(new LogoutRequestContext(form));
        } catch (ClientPolicyException cpe) {
            throw new ErrorResponseException(Errors.INVALID_REQUEST, cpe.getErrorDetail(), Response.Status.BAD_REQUEST);
        }
```
might be modified as follows.

```
        try {
            session.clientPolicy().triggerOnEvent(new LogoutRequestContext(form));
        } catch (ClientPolicyException cpe) {
            if (MtlsHoKTokenUtil.CERT_VERIFY_ERROR_DESC.equals(cpe.getErrorDetail())) {
                throw new ErrorResponseException(e.getError(), e.getErrorDetail(), Response.Status.UNAUTHORIZED);
            }
            throw new ErrorResponseException(Errors.INVALID_REQUEST, cpe.getErrorDetail(), Response.Status.BAD_REQUEST);
        }
```

### Arquillian Integration Test
You need to add the test case to `ClientPolicyBasicsTest`. For tests using mutual TLS, it might be helpful to refer to `HoKTest`.

**Comment by HryhoriiHevorkian** [comment]
Hello, @tnorimat . Everything is seems to be understandable for me, except several things:
1. In the method `verifyTokenBindingWithClientCertificate` we have to pass the HTTP request. How can I obtain this request in my `HolderOfKeyEnforceExecutor` class?
2. I have noticed, that in `ClientPolicyBasicTest` class, some enforcers are tested with the definite conditions (which are created manually and set some pre-defined data). Should I use certain condition to prepare the test for every of mine executor event?

Thanks for the clarification!

**Comment by tnorimat** [comment]
@HryhoriiHevorkian  Hello.

As for 1, to extract 'HttpRequest' in an executor, how about the following code?
```
HttpRequest httpRequest = session.getContext().getContextObject(HttpRequest.class);
```
Every executor has `KeycloakSession session` as its member.

As for 2, yes, could you prepare some conditions to control this executor's activation?

**Comment by HryhoriiHevorkian** [comment]
Hello, @tnorimat 
I have updated my PR, but I'm not pretty sure that I have understood the enforcer logic for 100%. Could you please review it?
https://github.com/tnorimat/keycloak/pull/15

Thank you for the upper clarification!

**Comment by tnorimat** [comment]
merged. https://github.com/keycloak/keycloak/pull/7699
