### ISSUE TITLE
Client Policy - Executor : Enforce secure signature algorithm for Signed JWT client authentication

### ISSUE THREAD

**Issue by tnorimat** [keycloak/kc-sig-fapi#91]
This issue is about [KEYCLOAK-14202 Client Policy - Executor : Enforce secure signature algorithm for Signed JWT client authentication](https://issues.redhat.com/browse/KEYCLOAK-14202) in [KEYCLOAK-13933 Client Policies](https://issues.redhat.com/browse/KEYCLOAK-13933).

The goal of this project are the followings.
- support policy executors defined in [Client Policy design document](https://github.com/keycloak/keycloak-community/blob/master/design/client-policies.md#which-kind-of-executors-are-provided)

The support detail can be found its [JIRA ticket](https://issues.redhat.com/browse/KEYCLOAK-14202).

**Comment by andriimurashkin** [comment]
Hello, please assign this task me.

**Comment by VinodAnandan** [comment]
Thank you @andriimurashkin

**Comment by tnorimat** [comment]
merged on tnorimat repository. https://github.com/tnorimat/keycloak/pull/14
 I will send this PR to keycloak upstream with `co-authored-by` trailer.

**Comment by tnorimat** [comment]
merged. https://github.com/keycloak/keycloak/pull/7682
