### ISSUE TITLE
Sync development contribution with Banfico and IntegralTech

### ISSUE THREAD

**Issue by VinodAnandan** [keycloak/kc-sig-fapi#95]
- [x] IntegralTech to provide appropriate access to Banfico developers. //@brothwellIntegral
- [x] Banfico Developers to submit pull requests to integraltech. //@arunganesh-a
- [x] IntegralTech to review the pull request and accept. //@brothwellIntegral
- [x] IntegralTech to synch with upstream changes on their repo. //@brothwellIntegral
- [x] IntegralTech to submit the upstream pull request in a `Co-authored-by` trailer. //@brothwellIntegral

Cc @brothwellIntegral @kannan-ra @arunganesh-a @pritish-nitb

**Comment by arunganesh-a** [comment]
We have got the access for the repository and have sent a pull request with the changes that we have done.

**Comment by brothwellIntegral** [comment]
We have synced the fork and are going through a code review process in our fork's master branch. Hoping to complete this on Monday.

**Comment by brothwellIntegral** [comment]
PR submitted at https://github.com/keycloak/kc-sig-fapi/pull/109

**Comment by VinodAnandan** [comment]
Closing this.

Thank you @brothwellIntegral @danagain @kannan-ra @arunganesh-a @pritish-nitb @tnorimat @dan
